/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Agente.Agente;
import Agente.AgenteHorario.AsignacionHorario;
import Agente.AgenteHorario.Tiempo;
import BusquedaLocal.EnfriamientoSimulado.EnfriamientoSimulado;
import Evaluacion.Evaluador;
import Evaluacion.EvaluadorAgenteHorario;
import GeneradorPoblacion.GeneradorPoblacionAgenteHorario;
import GestorArchivos.LectorArchivosHorarios;
import Memetico.AlgoritmoMemetico;
import Memetico.RTRHorariosUniversidad;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author acer_acer
 */
public class GUIHorarios extends javax.swing.JFrame {

    /**
     * Creates new form GUIHorarios
     */
    AlgoritmoMemetico memetico;
    LectorArchivosHorarios lector;
    GeneradorPoblacionAgenteHorario generador;
    Evaluador evaluador;
    EnfriamientoSimulado algoritmo;

    public GUIHorarios() {
        initComponents();
        this.setSize(851, 500);
        memetico = new AlgoritmoMemetico();
        lector = new LectorArchivosHorarios();
        generador = new GeneradorPoblacionAgenteHorario(lector.leerCursos(), lector.leerSalonesSimple(), new Tiempo(), 105);
        evaluador = new EvaluadorAgenteHorario();
        algoritmo = new EnfriamientoSimulado();
        cargarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaTabs = new javax.swing.JTabbedPane();
        pnlSem1 = new javax.swing.JPanel();
        a1 = new javax.swing.JTextArea();
        a2 = new javax.swing.JTextArea();
        a3 = new javax.swing.JTextArea();
        a4 = new javax.swing.JTextArea();
        a5 = new javax.swing.JTextArea();
        a6 = new javax.swing.JTextArea();
        a7 = new javax.swing.JTextArea();
        a8 = new javax.swing.JTextArea();
        a9 = new javax.swing.JTextArea();
        a10 = new javax.swing.JTextArea();
        a11 = new javax.swing.JTextArea();
        a12 = new javax.swing.JTextArea();
        a13 = new javax.swing.JTextArea();
        a14 = new javax.swing.JTextArea();
        a15 = new javax.swing.JTextArea();
        a16 = new javax.swing.JTextArea();
        a17 = new javax.swing.JTextArea();
        a18 = new javax.swing.JTextArea();
        a19 = new javax.swing.JTextArea();
        a20 = new javax.swing.JTextArea();
        a21 = new javax.swing.JTextArea();
        a22 = new javax.swing.JTextArea();
        a23 = new javax.swing.JTextArea();
        a24 = new javax.swing.JTextArea();
        a25 = new javax.swing.JTextArea();
        a26 = new javax.swing.JTextArea();
        a27 = new javax.swing.JTextArea();
        a28 = new javax.swing.JTextArea();
        a29 = new javax.swing.JTextArea();
        a30 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        pnlSem2 = new javax.swing.JPanel();
        a31 = new javax.swing.JTextArea();
        a32 = new javax.swing.JTextArea();
        a33 = new javax.swing.JTextArea();
        a34 = new javax.swing.JTextArea();
        a35 = new javax.swing.JTextArea();
        a36 = new javax.swing.JTextArea();
        a37 = new javax.swing.JTextArea();
        a38 = new javax.swing.JTextArea();
        a39 = new javax.swing.JTextArea();
        a40 = new javax.swing.JTextArea();
        a41 = new javax.swing.JTextArea();
        a42 = new javax.swing.JTextArea();
        a43 = new javax.swing.JTextArea();
        a44 = new javax.swing.JTextArea();
        a45 = new javax.swing.JTextArea();
        a46 = new javax.swing.JTextArea();
        a47 = new javax.swing.JTextArea();
        a48 = new javax.swing.JTextArea();
        a49 = new javax.swing.JTextArea();
        a50 = new javax.swing.JTextArea();
        a51 = new javax.swing.JTextArea();
        a52 = new javax.swing.JTextArea();
        a53 = new javax.swing.JTextArea();
        a54 = new javax.swing.JTextArea();
        a55 = new javax.swing.JTextArea();
        a56 = new javax.swing.JTextArea();
        a57 = new javax.swing.JTextArea();
        a58 = new javax.swing.JTextArea();
        a59 = new javax.swing.JTextArea();
        a60 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tablaTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        pnlSem1.setLayout(null);

        a1.setEditable(false);
        a1.setColumns(20);
        a1.setRows(5);
        a1.setBorder(null);
        a1.setOpaque(false);
        pnlSem1.add(a1);
        a1.setBounds(180, 80, 100, 40);

        a2.setEditable(false);
        a2.setColumns(20);
        a2.setRows(5);
        a2.setBorder(null);
        a2.setOpaque(false);
        pnlSem1.add(a2);
        a2.setBounds(290, 80, 100, 40);

        a3.setEditable(false);
        a3.setColumns(20);
        a3.setRows(5);
        a3.setBorder(null);
        a3.setOpaque(false);
        pnlSem1.add(a3);
        a3.setBounds(400, 80, 100, 40);

        a4.setEditable(false);
        a4.setColumns(20);
        a4.setRows(5);
        a4.setBorder(null);
        a4.setOpaque(false);
        pnlSem1.add(a4);
        a4.setBounds(500, 80, 100, 40);

        a5.setEditable(false);
        a5.setColumns(20);
        a5.setRows(5);
        a5.setBorder(null);
        a5.setOpaque(false);
        pnlSem1.add(a5);
        a5.setBounds(610, 80, 100, 40);

        a6.setEditable(false);
        a6.setColumns(20);
        a6.setRows(5);
        a6.setBorder(null);
        a6.setOpaque(false);
        pnlSem1.add(a6);
        a6.setBounds(180, 130, 100, 40);

        a7.setEditable(false);
        a7.setColumns(20);
        a7.setRows(5);
        a7.setBorder(null);
        a7.setOpaque(false);
        pnlSem1.add(a7);
        a7.setBounds(290, 130, 100, 40);

        a8.setEditable(false);
        a8.setColumns(20);
        a8.setRows(5);
        a8.setBorder(null);
        a8.setOpaque(false);
        pnlSem1.add(a8);
        a8.setBounds(400, 130, 100, 40);

        a9.setEditable(false);
        a9.setColumns(20);
        a9.setRows(5);
        a9.setBorder(null);
        a9.setOpaque(false);
        pnlSem1.add(a9);
        a9.setBounds(500, 130, 100, 40);

        a10.setEditable(false);
        a10.setColumns(20);
        a10.setRows(5);
        a10.setBorder(null);
        a10.setOpaque(false);
        pnlSem1.add(a10);
        a10.setBounds(610, 130, 100, 40);

        a11.setEditable(false);
        a11.setColumns(20);
        a11.setRows(5);
        a11.setBorder(null);
        a11.setOpaque(false);
        pnlSem1.add(a11);
        a11.setBounds(180, 180, 100, 40);

        a12.setEditable(false);
        a12.setColumns(20);
        a12.setRows(5);
        a12.setBorder(null);
        a12.setOpaque(false);
        pnlSem1.add(a12);
        a12.setBounds(290, 180, 100, 40);

        a13.setEditable(false);
        a13.setColumns(20);
        a13.setRows(5);
        a13.setBorder(null);
        a13.setOpaque(false);
        pnlSem1.add(a13);
        a13.setBounds(400, 180, 100, 40);

        a14.setEditable(false);
        a14.setColumns(20);
        a14.setRows(5);
        a14.setBorder(null);
        a14.setOpaque(false);
        pnlSem1.add(a14);
        a14.setBounds(500, 180, 100, 40);

        a15.setEditable(false);
        a15.setColumns(20);
        a15.setRows(5);
        a15.setBorder(null);
        a15.setOpaque(false);
        pnlSem1.add(a15);
        a15.setBounds(610, 180, 100, 40);

        a16.setEditable(false);
        a16.setColumns(20);
        a16.setRows(5);
        a16.setBorder(null);
        a16.setOpaque(false);
        pnlSem1.add(a16);
        a16.setBounds(180, 230, 100, 40);

        a17.setEditable(false);
        a17.setColumns(20);
        a17.setRows(5);
        a17.setBorder(null);
        a17.setOpaque(false);
        pnlSem1.add(a17);
        a17.setBounds(290, 230, 100, 40);

        a18.setEditable(false);
        a18.setColumns(20);
        a18.setRows(5);
        a18.setBorder(null);
        a18.setOpaque(false);
        pnlSem1.add(a18);
        a18.setBounds(400, 230, 100, 40);

        a19.setEditable(false);
        a19.setColumns(20);
        a19.setRows(5);
        a19.setBorder(null);
        a19.setOpaque(false);
        pnlSem1.add(a19);
        a19.setBounds(500, 230, 100, 40);

        a20.setEditable(false);
        a20.setColumns(20);
        a20.setRows(5);
        a20.setBorder(null);
        a20.setOpaque(false);
        pnlSem1.add(a20);
        a20.setBounds(610, 230, 100, 40);

        a21.setEditable(false);
        a21.setColumns(20);
        a21.setRows(5);
        a21.setBorder(null);
        a21.setOpaque(false);
        pnlSem1.add(a21);
        a21.setBounds(180, 280, 100, 40);

        a22.setEditable(false);
        a22.setColumns(20);
        a22.setRows(5);
        a22.setBorder(null);
        a22.setOpaque(false);
        pnlSem1.add(a22);
        a22.setBounds(290, 280, 100, 40);

        a23.setEditable(false);
        a23.setColumns(20);
        a23.setRows(5);
        a23.setBorder(null);
        a23.setOpaque(false);
        pnlSem1.add(a23);
        a23.setBounds(400, 280, 100, 40);

        a24.setEditable(false);
        a24.setColumns(20);
        a24.setRows(5);
        a24.setBorder(null);
        a24.setOpaque(false);
        pnlSem1.add(a24);
        a24.setBounds(500, 280, 100, 40);

        a25.setEditable(false);
        a25.setColumns(20);
        a25.setRows(5);
        a25.setBorder(null);
        a25.setOpaque(false);
        pnlSem1.add(a25);
        a25.setBounds(610, 280, 100, 40);

        a26.setEditable(false);
        a26.setColumns(20);
        a26.setRows(5);
        a26.setBorder(null);
        a26.setOpaque(false);
        pnlSem1.add(a26);
        a26.setBounds(180, 330, 100, 40);

        a27.setEditable(false);
        a27.setColumns(20);
        a27.setRows(5);
        a27.setBorder(null);
        a27.setOpaque(false);
        pnlSem1.add(a27);
        a27.setBounds(290, 330, 100, 40);

        a28.setEditable(false);
        a28.setColumns(20);
        a28.setRows(5);
        a28.setBorder(null);
        a28.setOpaque(false);
        pnlSem1.add(a28);
        a28.setBounds(400, 330, 100, 40);

        a29.setEditable(false);
        a29.setColumns(20);
        a29.setRows(5);
        a29.setBorder(null);
        a29.setOpaque(false);
        pnlSem1.add(a29);
        a29.setBounds(500, 330, 100, 40);

        a30.setEditable(false);
        a30.setColumns(20);
        a30.setRows(5);
        a30.setBorder(null);
        a30.setOpaque(false);
        pnlSem1.add(a30);
        a30.setBounds(610, 330, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/horarioUniversidad.jpg"))); // NOI18N
        pnlSem1.add(jLabel1);
        jLabel1.setBounds(20, 0, 760, 420);

        tablaTabs.addTab("Semestre 1", pnlSem1);

        pnlSem2.setLayout(null);

        a31.setEditable(false);
        a31.setColumns(20);
        a31.setRows(5);
        a31.setBorder(null);
        a31.setOpaque(false);
        pnlSem2.add(a31);
        a31.setBounds(180, 80, 100, 40);

        a32.setEditable(false);
        a32.setColumns(20);
        a32.setRows(5);
        a32.setBorder(null);
        a32.setOpaque(false);
        pnlSem2.add(a32);
        a32.setBounds(290, 80, 100, 40);

        a33.setEditable(false);
        a33.setColumns(20);
        a33.setRows(5);
        a33.setBorder(null);
        a33.setOpaque(false);
        pnlSem2.add(a33);
        a33.setBounds(400, 80, 100, 40);

        a34.setEditable(false);
        a34.setColumns(20);
        a34.setRows(5);
        a34.setBorder(null);
        a34.setOpaque(false);
        pnlSem2.add(a34);
        a34.setBounds(500, 80, 100, 40);

        a35.setEditable(false);
        a35.setColumns(20);
        a35.setRows(5);
        a35.setBorder(null);
        a35.setOpaque(false);
        pnlSem2.add(a35);
        a35.setBounds(610, 80, 100, 40);

        a36.setEditable(false);
        a36.setColumns(20);
        a36.setRows(5);
        a36.setBorder(null);
        a36.setOpaque(false);
        pnlSem2.add(a36);
        a36.setBounds(180, 130, 100, 40);

        a37.setEditable(false);
        a37.setColumns(20);
        a37.setRows(5);
        a37.setBorder(null);
        a37.setOpaque(false);
        pnlSem2.add(a37);
        a37.setBounds(290, 130, 100, 40);

        a38.setEditable(false);
        a38.setColumns(20);
        a38.setRows(5);
        a38.setBorder(null);
        a38.setOpaque(false);
        pnlSem2.add(a38);
        a38.setBounds(400, 130, 100, 40);

        a39.setEditable(false);
        a39.setColumns(20);
        a39.setRows(5);
        a39.setBorder(null);
        a39.setOpaque(false);
        pnlSem2.add(a39);
        a39.setBounds(500, 130, 100, 40);

        a40.setEditable(false);
        a40.setColumns(20);
        a40.setRows(5);
        a40.setBorder(null);
        a40.setOpaque(false);
        pnlSem2.add(a40);
        a40.setBounds(610, 130, 100, 40);

        a41.setEditable(false);
        a41.setColumns(20);
        a41.setRows(5);
        a41.setBorder(null);
        a41.setOpaque(false);
        pnlSem2.add(a41);
        a41.setBounds(180, 180, 100, 40);

        a42.setEditable(false);
        a42.setColumns(20);
        a42.setRows(5);
        a42.setBorder(null);
        a42.setOpaque(false);
        pnlSem2.add(a42);
        a42.setBounds(290, 180, 100, 40);

        a43.setEditable(false);
        a43.setColumns(20);
        a43.setRows(5);
        a43.setBorder(null);
        a43.setOpaque(false);
        pnlSem2.add(a43);
        a43.setBounds(400, 180, 100, 40);

        a44.setEditable(false);
        a44.setColumns(20);
        a44.setRows(5);
        a44.setBorder(null);
        a44.setOpaque(false);
        pnlSem2.add(a44);
        a44.setBounds(500, 180, 100, 40);

        a45.setEditable(false);
        a45.setColumns(20);
        a45.setRows(5);
        a45.setBorder(null);
        a45.setOpaque(false);
        pnlSem2.add(a45);
        a45.setBounds(610, 180, 100, 40);

        a46.setEditable(false);
        a46.setColumns(20);
        a46.setRows(5);
        a46.setBorder(null);
        a46.setOpaque(false);
        pnlSem2.add(a46);
        a46.setBounds(180, 230, 100, 40);

        a47.setEditable(false);
        a47.setColumns(20);
        a47.setRows(5);
        a47.setBorder(null);
        a47.setOpaque(false);
        pnlSem2.add(a47);
        a47.setBounds(290, 230, 100, 40);

        a48.setEditable(false);
        a48.setColumns(20);
        a48.setRows(5);
        a48.setBorder(null);
        a48.setOpaque(false);
        pnlSem2.add(a48);
        a48.setBounds(400, 230, 100, 40);

        a49.setEditable(false);
        a49.setColumns(20);
        a49.setRows(5);
        a49.setBorder(null);
        a49.setOpaque(false);
        pnlSem2.add(a49);
        a49.setBounds(500, 230, 100, 40);

        a50.setEditable(false);
        a50.setColumns(20);
        a50.setRows(5);
        a50.setBorder(null);
        a50.setOpaque(false);
        pnlSem2.add(a50);
        a50.setBounds(610, 230, 100, 40);

        a51.setEditable(false);
        a51.setColumns(20);
        a51.setRows(5);
        a51.setBorder(null);
        a51.setOpaque(false);
        pnlSem2.add(a51);
        a51.setBounds(180, 280, 100, 40);

        a52.setEditable(false);
        a52.setColumns(20);
        a52.setRows(5);
        a52.setBorder(null);
        a52.setOpaque(false);
        pnlSem2.add(a52);
        a52.setBounds(290, 280, 100, 40);

        a53.setEditable(false);
        a53.setColumns(20);
        a53.setRows(5);
        a53.setBorder(null);
        a53.setOpaque(false);
        pnlSem2.add(a53);
        a53.setBounds(400, 280, 100, 40);

        a54.setEditable(false);
        a54.setColumns(20);
        a54.setRows(5);
        a54.setBorder(null);
        a54.setOpaque(false);
        pnlSem2.add(a54);
        a54.setBounds(500, 280, 100, 40);

        a55.setEditable(false);
        a55.setColumns(20);
        a55.setRows(5);
        a55.setBorder(null);
        a55.setOpaque(false);
        pnlSem2.add(a55);
        a55.setBounds(610, 280, 100, 40);

        a56.setEditable(false);
        a56.setColumns(20);
        a56.setRows(5);
        a56.setBorder(null);
        a56.setOpaque(false);
        pnlSem2.add(a56);
        a56.setBounds(180, 330, 100, 40);

        a57.setEditable(false);
        a57.setColumns(20);
        a57.setRows(5);
        a57.setBorder(null);
        a57.setOpaque(false);
        pnlSem2.add(a57);
        a57.setBounds(290, 330, 100, 40);

        a58.setEditable(false);
        a58.setColumns(20);
        a58.setRows(5);
        a58.setBorder(null);
        a58.setOpaque(false);
        pnlSem2.add(a58);
        a58.setBounds(400, 330, 100, 40);

        a59.setEditable(false);
        a59.setColumns(20);
        a59.setRows(5);
        a59.setBorder(null);
        a59.setOpaque(false);
        pnlSem2.add(a59);
        a59.setBounds(500, 330, 100, 40);

        a60.setEditable(false);
        a60.setColumns(20);
        a60.setRows(5);
        a60.setBorder(null);
        a60.setOpaque(false);
        pnlSem2.add(a60);
        a60.setBounds(610, 330, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/horarioUniversidad.jpg"))); // NOI18N
        pnlSem2.add(jLabel2);
        jLabel2.setBounds(20, 0, 760, 420);

        tablaTabs.addTab("Semestre 1", pnlSem2);

        getContentPane().add(tablaTabs);
        tablaTabs.setBounds(0, 0, 840, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarValores() {
        Component[] components = pnlSem1.getComponents();
        List<Component> asList = Arrays.asList(components);
        Agente resultado = memetico.ejecutar(generador, 600, 5, new RTRHorariosUniversidad(), algoritmo, evaluador, "universidad", 800);
        ArrayList<Object> memes = resultado.getMemes();
        for (int i = 0; i < 16; i++) {
            int pos;
            AsignacionHorario horario = (AsignacionHorario) memes.get(i);
            String informacion;
            for (int j = 0; j < horario.getFranjasHorario().size(); j++) {
                informacion = horario.getCurso().getNombreCurso() + "-" + horario.getCurso().getGrupo();
                pos = posicionHorario(horario.getFranjasHorario().get(j).getDia(), horario.getFranjasHorario().get(j).getHora());
                JTextArea tmp = (JTextArea) asList.get(pos);
                informacion += "-" + horario.getFranjasHorario().get(j).getSalon().getIdentifacador();
                tmp.setFont(new Font("Arial", Font.PLAIN, 12));
                if ("".equals(tmp.getText())) {
                    tmp.setText(informacion);
                } else {
                    tmp.setText(tmp.getText() + "\n" + informacion);
                }
            }
        }
        //Semestre 2
        components = pnlSem2.getComponents();
        asList = Arrays.asList(components);
        for (int i = 16; i < 5; i++) {
            int pos;
            AsignacionHorario horario = (AsignacionHorario) memes.get(i);
            String informacion;
            for (int j = 0; j < horario.getFranjasHorario().size(); j++) {
                informacion = horario.getCurso().getNombreCurso() + "-" + horario.getCurso().getGrupo();
                pos = posicionHorario(horario.getFranjasHorario().get(j).getDia(), horario.getFranjasHorario().get(j).getHora());
                JTextArea tmp = (JTextArea) asList.get(pos);
                informacion += "-" + horario.getFranjasHorario().get(j).getSalon().getIdentifacador();
                tmp.setFont(new Font("Arial", Font.PLAIN, 12));
                if ("".equals(tmp.getText())) {
                    tmp.setText(informacion);
                } else {
                    tmp.setText(tmp.getText() + "\n" + informacion);
                }
            }
        }
        System.out.println("VALORESSS");
//        Agente resultado = memetico.ejecutar(generador, 600, 5, new RTRHorariosUniversidad(), algoritmo, evaluador, "universidad", 800);
//        a1.setText("<html>&ensp;&ensp;Calculoaaa-FG<br>&ensp;&ensp;MarlbenBendec</html>");
//        ArrayList<Object> memes = resultado.getMemes();
//        for (int i = 0; i < memes.size(); i++) {
//            AsignacionHorario horario=(AsignacionHorario) memes.get(i);
//            System.out.println("Curso:"+ horario.getCurso().getNombreCurso()+"Grupo:"+horario.getCurso().getGrupo());
//            for (int j= 0; j< horario.getFranjasHorario().size(); j++) {
//                System.out.println("Dia"+horario.getFranjasHorario().get(j).getDia()+"Hora"+horario.getFranjasHorario().get(j).getHora());
//            }
//        }
    }

    public int posicionHorario(int dia, int hora) {
        switch (hora) {
            case 7:
                hora = 0;
                break;
            case 9:
                hora = 1;
                break;
            case 11:
                hora = 2;
                break;
            case 14:
                hora = 3;
                break;
            case 16:
                hora = 4;
                break;
            case 18:
                hora = 5;
                break;
        }
        return dia + (5 * hora);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a1;
    private javax.swing.JTextArea a10;
    private javax.swing.JTextArea a11;
    private javax.swing.JTextArea a12;
    private javax.swing.JTextArea a13;
    private javax.swing.JTextArea a14;
    private javax.swing.JTextArea a15;
    private javax.swing.JTextArea a16;
    private javax.swing.JTextArea a17;
    private javax.swing.JTextArea a18;
    private javax.swing.JTextArea a19;
    private javax.swing.JTextArea a2;
    private javax.swing.JTextArea a20;
    private javax.swing.JTextArea a21;
    private javax.swing.JTextArea a22;
    private javax.swing.JTextArea a23;
    private javax.swing.JTextArea a24;
    private javax.swing.JTextArea a25;
    private javax.swing.JTextArea a26;
    private javax.swing.JTextArea a27;
    private javax.swing.JTextArea a28;
    private javax.swing.JTextArea a29;
    private javax.swing.JTextArea a3;
    private javax.swing.JTextArea a30;
    private javax.swing.JTextArea a31;
    private javax.swing.JTextArea a32;
    private javax.swing.JTextArea a33;
    private javax.swing.JTextArea a34;
    private javax.swing.JTextArea a35;
    private javax.swing.JTextArea a36;
    private javax.swing.JTextArea a37;
    private javax.swing.JTextArea a38;
    private javax.swing.JTextArea a39;
    private javax.swing.JTextArea a4;
    private javax.swing.JTextArea a40;
    private javax.swing.JTextArea a41;
    private javax.swing.JTextArea a42;
    private javax.swing.JTextArea a43;
    private javax.swing.JTextArea a44;
    private javax.swing.JTextArea a45;
    private javax.swing.JTextArea a46;
    private javax.swing.JTextArea a47;
    private javax.swing.JTextArea a48;
    private javax.swing.JTextArea a49;
    private javax.swing.JTextArea a5;
    private javax.swing.JTextArea a50;
    private javax.swing.JTextArea a51;
    private javax.swing.JTextArea a52;
    private javax.swing.JTextArea a53;
    private javax.swing.JTextArea a54;
    private javax.swing.JTextArea a55;
    private javax.swing.JTextArea a56;
    private javax.swing.JTextArea a57;
    private javax.swing.JTextArea a58;
    private javax.swing.JTextArea a59;
    private javax.swing.JTextArea a6;
    private javax.swing.JTextArea a60;
    private javax.swing.JTextArea a7;
    private javax.swing.JTextArea a8;
    private javax.swing.JTextArea a9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlSem1;
    private javax.swing.JPanel pnlSem2;
    private javax.swing.JTabbedPane tablaTabs;
    // End of variables declaration//GEN-END:variables

}
