/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Agente.Agente;
import Agente.AgenteHorario.AsignacionHorario;
import Agente.AgenteHorario.Tiempo;
import BusquedaLocal.EnfriamientoSimulado.EnfriamientoSimulado;
import Evaluacion.Evaluador;
import Evaluacion.EvaluadorAgenteHorario;
import GeneradorPoblacion.GeneradorPoblacionAgenteHorario;
import GestorArchivos.LectorArchivosHorarios;
import Memetico.AlgoritmoMemetico;
import Memetico.RTRHorariosUniversidad;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author acer_acer
 */
public class GUIHorarios extends javax.swing.JDialog {

    /**
     * Creates new form GUIHorarios
     */
    AlgoritmoMemetico memetico;
    LectorArchivosHorarios lector;
    GeneradorPoblacionAgenteHorario generador;
    Evaluador evaluador;
    EnfriamientoSimulado algoritmo;

    public GUIHorarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(851, 500);
        memetico = new AlgoritmoMemetico();
        lector = new LectorArchivosHorarios();
        generador = new GeneradorPoblacionAgenteHorario(lector.leerCursos(), lector.leerSalonesSimple(), new Tiempo(), 105);
        evaluador = new EvaluadorAgenteHorario();
        algoritmo = new EnfriamientoSimulado();
       cargarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaTabs = new javax.swing.JTabbedPane();
        pnlSem1 = new javax.swing.JPanel();
        a1 = new javax.swing.JTextArea();
        a2 = new javax.swing.JTextArea();
        a3 = new javax.swing.JTextArea();
        a4 = new javax.swing.JTextArea();
        a5 = new javax.swing.JTextArea();
        a6 = new javax.swing.JTextArea();
        a7 = new javax.swing.JTextArea();
        a8 = new javax.swing.JTextArea();
        a9 = new javax.swing.JTextArea();
        a10 = new javax.swing.JTextArea();
        a11 = new javax.swing.JTextArea();
        a12 = new javax.swing.JTextArea();
        a13 = new javax.swing.JTextArea();
        a14 = new javax.swing.JTextArea();
        a15 = new javax.swing.JTextArea();
        a16 = new javax.swing.JTextArea();
        a17 = new javax.swing.JTextArea();
        a18 = new javax.swing.JTextArea();
        a19 = new javax.swing.JTextArea();
        a20 = new javax.swing.JTextArea();
        a21 = new javax.swing.JTextArea();
        a22 = new javax.swing.JTextArea();
        a23 = new javax.swing.JTextArea();
        a24 = new javax.swing.JTextArea();
        a25 = new javax.swing.JTextArea();
        a26 = new javax.swing.JTextArea();
        a27 = new javax.swing.JTextArea();
        a28 = new javax.swing.JTextArea();
        a29 = new javax.swing.JTextArea();
        a30 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tablaTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        pnlSem1.setLayout(null);

        a1.setEditable(false);
        a1.setColumns(20);
        a1.setRows(5);
        a1.setBorder(null);
        a1.setOpaque(false);
        pnlSem1.add(a1);
        a1.setBounds(180, 80, 100, 40);

        a2.setEditable(false);
        a2.setColumns(20);
        a2.setRows(5);
        a2.setBorder(null);
        a2.setOpaque(false);
        pnlSem1.add(a2);
        a2.setBounds(290, 80, 100, 40);

        a3.setEditable(false);
        a3.setColumns(20);
        a3.setRows(5);
        a3.setBorder(null);
        a3.setOpaque(false);
        pnlSem1.add(a3);
        a3.setBounds(400, 80, 100, 40);

        a4.setEditable(false);
        a4.setColumns(20);
        a4.setRows(5);
        a4.setBorder(null);
        a4.setOpaque(false);
        pnlSem1.add(a4);
        a4.setBounds(500, 80, 100, 40);

        a5.setEditable(false);
        a5.setColumns(20);
        a5.setRows(5);
        a5.setBorder(null);
        a5.setOpaque(false);
        pnlSem1.add(a5);
        a5.setBounds(610, 80, 100, 40);

        a6.setEditable(false);
        a6.setColumns(20);
        a6.setRows(5);
        a6.setBorder(null);
        a6.setOpaque(false);
        pnlSem1.add(a6);
        a6.setBounds(180, 130, 100, 40);

        a7.setEditable(false);
        a7.setColumns(20);
        a7.setRows(5);
        a7.setBorder(null);
        a7.setOpaque(false);
        pnlSem1.add(a7);
        a7.setBounds(290, 130, 100, 40);

        a8.setEditable(false);
        a8.setColumns(20);
        a8.setRows(5);
        a8.setBorder(null);
        a8.setOpaque(false);
        pnlSem1.add(a8);
        a8.setBounds(400, 130, 100, 40);

        a9.setEditable(false);
        a9.setColumns(20);
        a9.setRows(5);
        a9.setBorder(null);
        a9.setOpaque(false);
        pnlSem1.add(a9);
        a9.setBounds(500, 130, 100, 40);

        a10.setEditable(false);
        a10.setColumns(20);
        a10.setRows(5);
        a10.setBorder(null);
        a10.setOpaque(false);
        pnlSem1.add(a10);
        a10.setBounds(610, 130, 100, 40);

        a11.setEditable(false);
        a11.setColumns(20);
        a11.setRows(5);
        a11.setBorder(null);
        a11.setOpaque(false);
        pnlSem1.add(a11);
        a11.setBounds(180, 180, 100, 40);

        a12.setEditable(false);
        a12.setColumns(20);
        a12.setRows(5);
        a12.setBorder(null);
        a12.setOpaque(false);
        pnlSem1.add(a12);
        a12.setBounds(290, 180, 100, 40);

        a13.setEditable(false);
        a13.setColumns(20);
        a13.setRows(5);
        a13.setBorder(null);
        a13.setOpaque(false);
        pnlSem1.add(a13);
        a13.setBounds(400, 180, 100, 40);

        a14.setEditable(false);
        a14.setColumns(20);
        a14.setRows(5);
        a14.setBorder(null);
        a14.setOpaque(false);
        pnlSem1.add(a14);
        a14.setBounds(500, 180, 100, 40);

        a15.setEditable(false);
        a15.setColumns(20);
        a15.setRows(5);
        a15.setBorder(null);
        a15.setOpaque(false);
        pnlSem1.add(a15);
        a15.setBounds(610, 180, 100, 40);

        a16.setEditable(false);
        a16.setColumns(20);
        a16.setRows(5);
        a16.setBorder(null);
        a16.setOpaque(false);
        pnlSem1.add(a16);
        a16.setBounds(180, 230, 100, 40);

        a17.setEditable(false);
        a17.setColumns(20);
        a17.setRows(5);
        a17.setBorder(null);
        a17.setOpaque(false);
        pnlSem1.add(a17);
        a17.setBounds(290, 230, 100, 40);

        a18.setEditable(false);
        a18.setColumns(20);
        a18.setRows(5);
        a18.setBorder(null);
        a18.setOpaque(false);
        pnlSem1.add(a18);
        a18.setBounds(400, 230, 100, 40);

        a19.setEditable(false);
        a19.setColumns(20);
        a19.setRows(5);
        a19.setBorder(null);
        a19.setOpaque(false);
        pnlSem1.add(a19);
        a19.setBounds(500, 230, 100, 40);

        a20.setEditable(false);
        a20.setColumns(20);
        a20.setRows(5);
        a20.setBorder(null);
        a20.setOpaque(false);
        pnlSem1.add(a20);
        a20.setBounds(610, 230, 100, 40);

        a21.setEditable(false);
        a21.setColumns(20);
        a21.setRows(5);
        a21.setBorder(null);
        a21.setOpaque(false);
        pnlSem1.add(a21);
        a21.setBounds(180, 280, 100, 40);

        a22.setEditable(false);
        a22.setColumns(20);
        a22.setRows(5);
        a22.setBorder(null);
        a22.setOpaque(false);
        pnlSem1.add(a22);
        a22.setBounds(290, 280, 100, 40);

        a23.setEditable(false);
        a23.setColumns(20);
        a23.setRows(5);
        a23.setBorder(null);
        a23.setOpaque(false);
        pnlSem1.add(a23);
        a23.setBounds(400, 280, 100, 40);

        a24.setEditable(false);
        a24.setColumns(20);
        a24.setRows(5);
        a24.setBorder(null);
        a24.setOpaque(false);
        pnlSem1.add(a24);
        a24.setBounds(500, 280, 100, 40);

        a25.setEditable(false);
        a25.setColumns(20);
        a25.setRows(5);
        a25.setBorder(null);
        a25.setOpaque(false);
        pnlSem1.add(a25);
        a25.setBounds(610, 280, 100, 40);

        a26.setEditable(false);
        a26.setColumns(20);
        a26.setRows(5);
        a26.setBorder(null);
        a26.setOpaque(false);
        pnlSem1.add(a26);
        a26.setBounds(180, 330, 100, 40);

        a27.setEditable(false);
        a27.setColumns(20);
        a27.setRows(5);
        a27.setBorder(null);
        a27.setOpaque(false);
        pnlSem1.add(a27);
        a27.setBounds(290, 330, 100, 40);

        a28.setEditable(false);
        a28.setColumns(20);
        a28.setRows(5);
        a28.setBorder(null);
        a28.setOpaque(false);
        pnlSem1.add(a28);
        a28.setBounds(400, 330, 100, 40);

        a29.setEditable(false);
        a29.setColumns(20);
        a29.setRows(5);
        a29.setBorder(null);
        a29.setOpaque(false);
        pnlSem1.add(a29);
        a29.setBounds(500, 330, 100, 40);

        a30.setEditable(false);
        a30.setColumns(20);
        a30.setRows(5);
        a30.setBorder(null);
        a30.setOpaque(false);
        pnlSem1.add(a30);
        a30.setBounds(610, 330, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/horarioUniversidad.jpg"))); // NOI18N
        pnlSem1.add(jLabel1);
        jLabel1.setBounds(20, 0, 760, 420);

        tablaTabs.addTab("Semestre 1", pnlSem1);

        getContentPane().add(tablaTabs);
        tablaTabs.setBounds(0, 0, 840, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarValores() {
        Component[] components = pnlSem1.getComponents();
        List<Component> asList = Arrays.asList(components);
        Agente resultado = memetico.ejecutar(generador, 600, 5, new RTRHorariosUniversidad(), algoritmo, evaluador, "universidad", 800);
        ArrayList<Object> memes = resultado.getMemes();
        for (int i = 0; i < 16; i++) {
            int pos;
            AsignacionHorario horario = (AsignacionHorario) memes.get(i);
            String informacion;
            for (int j = 0; j < horario.getFranjasHorario().size(); j++) {
                informacion = horario.getCurso().getNombreCurso() + "-" + horario.getCurso().getGrupo();
                pos=posicionHorario(horario.getFranjasHorario().get(j).getDia(), horario.getFranjasHorario().get(j).getHora());
                JTextArea tmp=(JTextArea)asList.get(pos);
                informacion+="-"+horario.getFranjasHorario().get(j).getSalon().getIdentifacador();
                tmp.setFont(new Font("Arial", Font.PLAIN, 12));
                if("".equals(tmp.getText())){
                    tmp.setText(informacion);
                }else{
                    tmp.setText(tmp.getText()+"\n"+informacion);
                }
            }
        }
        System.out.println("VALORESSS");
//        Agente resultado = memetico.ejecutar(generador, 600, 5, new RTRHorariosUniversidad(), algoritmo, evaluador, "universidad", 800);
//        a1.setText("<html>&ensp;&ensp;Calculoaaa-FG<br>&ensp;&ensp;MarlbenBendec</html>");
//        ArrayList<Object> memes = resultado.getMemes();
//        for (int i = 0; i < memes.size(); i++) {
//            AsignacionHorario horario=(AsignacionHorario) memes.get(i);
//            System.out.println("Curso:"+ horario.getCurso().getNombreCurso()+"Grupo:"+horario.getCurso().getGrupo());
//            for (int j= 0; j< horario.getFranjasHorario().size(); j++) {
//                System.out.println("Dia"+horario.getFranjasHorario().get(j).getDia()+"Hora"+horario.getFranjasHorario().get(j).getHora());
//            }
//        }
    }

    public int posicionHorario(int dia, int hora) {
        switch (hora) {
            case 7:
                hora = 0;
                break;
            case 9:
                hora = 1;
                break;
            case 11:
                hora = 2;
                break;
            case 14:
                hora = 3;
                break;
            case 16:
                hora = 4;
                break;
            case 18:
                hora = 5;
                break;
        }
        return dia + (5 * hora);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIHorarios dialog = new GUIHorarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a1;
    private javax.swing.JTextArea a10;
    private javax.swing.JTextArea a11;
    private javax.swing.JTextArea a12;
    private javax.swing.JTextArea a13;
    private javax.swing.JTextArea a14;
    private javax.swing.JTextArea a15;
    private javax.swing.JTextArea a16;
    private javax.swing.JTextArea a17;
    private javax.swing.JTextArea a18;
    private javax.swing.JTextArea a19;
    private javax.swing.JTextArea a2;
    private javax.swing.JTextArea a20;
    private javax.swing.JTextArea a21;
    private javax.swing.JTextArea a22;
    private javax.swing.JTextArea a23;
    private javax.swing.JTextArea a24;
    private javax.swing.JTextArea a25;
    private javax.swing.JTextArea a26;
    private javax.swing.JTextArea a27;
    private javax.swing.JTextArea a28;
    private javax.swing.JTextArea a29;
    private javax.swing.JTextArea a3;
    private javax.swing.JTextArea a30;
    private javax.swing.JTextArea a4;
    private javax.swing.JTextArea a5;
    private javax.swing.JTextArea a6;
    private javax.swing.JTextArea a7;
    private javax.swing.JTextArea a8;
    private javax.swing.JTextArea a9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlSem1;
    private javax.swing.JTabbedPane tablaTabs;
    // End of variables declaration//GEN-END:variables

}
